[versions]

kotlin = "1.7.0"
kotlin-stdlib = "1.7.10"
benchmark = "1.0.0"
camera-view = "1.2.1"

[libraries]

android-pluginGradle = "com.android.tools.build:gradle:7.1.0"

kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin-stdlib" }

androidx-appcompat = "androidx.appcompat:appcompat:1.2.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"
androidx-core = "androidx.core:core-ktx:1.3.2"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.1.0"

androidx-benchmark-pluginGradle = { module = "androidx.benchmark:benchmark-gradle-plugin", version.ref = "benchmark" }
androidx-benchmark-junit4 = { module = "androidx.benchmark:benchmark-junit4", version.ref = "benchmark" }

androidx-test-runner = "androidx.test:runner:1.2.0"
androidx-test-junit = "androidx.test.ext:junit:1.1.1"
test-junit = "junit:junit:4.12"
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera-view" }
