name: awesome_chewie
description: Cloudchewie UI/UX/Utils
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 控件
  fluttertoast: ^8.2.12
  flutter_animate: ^4.5.2
  auto_size_text: ^3.0.0
  lottie: ^3.3.1
  flutter_widget_from_html: ^0.15.0
  smart_snackbars:
    path: ../widget/smart_snackbars
  lucide_icons:
    path: ../widget/lucide_icons
  flutter_context_menu:
    path: ../widget/flutter_context_menu
  markdown_widget:
    path: ../widget/markdown_widget
  animated_custom_dropdown:
    path: ../widget/animated_custom_dropdown
  group_button:
    path: ../widget/group_button
  modal_bottom_sheet: ^3.0.0
  highlighting: ^0.9.0+11.8.0
  flutter_highlighting: ^0.9.0+11.8.0
  code_highlight_view: ^0.1.1
  markdown: ^7.3.0
  flutter_math_fork: ^0.7.3
  # 存储/网络
  path:
  logger: ^2.5.0
  hive: ^4.0.0-dev.2 # 轻量存储
  isar_flutter_libs: ^4.0.0-dev.13
  dio: ^5.8.0+1
  cookie_jar: ^4.0.8
  path_provider: ^2.0.12
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  local_proxy: ^0.0.3
  file_picker: ^8.3.1
  process_run: ^1.2.4
  # 系统
  provider: ^6.1.4
  local_auth: ^2.3.0
  local_auth_android: ^1.0.48
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.0
  app_links: ^6.4.0
  flutter_displaymode: ^0.6.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  install_plugin: ^2.1.0
  hotkey_manager: ^0.2.3
  flutter_inappwebview: 6.0.0
  # 工具
  intl: ^0.19.0
  intl_utils: ^2.8.7
  html: ^0.15.5+1
  uuid: ^4.4.2
  tuple: ^2.0.0
  encrypt: ^5.0.3
  pinyin: ^3.3.0
  pointycastle: 3.9.1
  palette_generator: ^0.3.3+3
  metadata_fetch: ^0.4.2
  path_drawing: ^1.0.1
  # 平台适配
  flutter_windowmanager: ^0.2.0
  responsive_builder: ^0.7.1
  window_manager: ^0.4.3
  restart_app: ^1.3.2
  local_notifier: ^0.1.6
  flutter_local_notifications: ^17.2.1+2
  screen_protector: ^1.4.2+1
  shell_executor: ^0.1.6 # 执行命令

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1

flutter_intl:
  enabled: true
  class_name: ChewieS
  main_locale: zh_CN
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated
  use_deferred_loading: false