name: flutter_resizable_container
description: Add nestable, resizable containers to your Flutter app with ease.
version: 4.0.1
homepage: https://github.com/andyhorn/flutter_resizable_container

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.0.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <6.0.0"
  mocktail: ^1.0.3
