name: s3_storage
description: S3 (AWS, MinIO) Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 1.0.4
homepage: https://github.com/MindMayhem/s3_storage
issue_tracker: https://github.com/MindMayhem/s3_storage

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.8.0
  http: ^1.2.1
  crypto: ^3.0.2
  convert: ^3.1.1
  xml: ^6.1.0
  buffer: ^1.1.1
  intl: ^0.19.0
  mime: ^1.0.2
  path: ^1.8.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  html: ^0.15.0
